# frozen_string_literal: true

source "https://rubygems.org"

gem "mastermind_generator"
gem "minitest", ">=5.14.3"
gem "minitest-reporters", ">= 0.5.0"
gem "rake", ">=13.0.3"
gem "rubocop", ">=1.8.1"
gem "rubocop-minitest", ">=0.10.3"
gem "simplecov", ">=0.21.2"
